name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Move to c-- comp directory
      run: cd c--
    - name: Install dependencies
      run: make c--.h

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
